title: nick quaranto ¤ coding with spice
author: Nick Quaranto
email: nick@quaran.to
url: https://quaran.to

permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - CC-LICENSE
  - MIT-LICENSE
  - vendor
